services:
  server:
    image: ghcr.io/mcp-agents-ai/mcp-agents-hub-server:latest
    restart: always
    container_name: mcp-agents-hub-server
    networks:
      - mcp-agents-hub
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ../.github-private/env_files/.env

  client:
    image: ghcr.io/mcp-agents-ai/mcp-agents-hub-client:latest
    restart: always
    container_name: mcp-agents-hub-client
    networks:
      - mcp-agents-hub
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../.github-private/ssl:/etc/nginx/ssl:ro
    depends_on:
      - server

networks:
  mcp-agents-hub:
    driver: bridge