version: '3.8'

services:
  server:
    image: mcp-marketplace-server
    build:
      context: ./server
    ports:
      - "3001:3001"
    environment:
      - PORT=3001

  client:
    image: mcp-marketplace-client
    build:
      context: ./client
    ports:
      - "80:80"
    depends_on:
      - server