version: '3.8'

services:
  server:
    image: ghcr.io/mcp-agents-ai/mcp-marketplace-server:latest
    build:
      context: ./server
    ports:
      - "3001:3001"
    environment:
      - PORT=3001

  client:
    image: ghcr.io/mcp-agents-ai/mcp-marketplace-client:latest
    build:
      context: ./client
    ports:
      - "80:80"
    depends_on:
      - server
