
services:
  server:
    image: ghcr.io/mcp-agents-ai/mcp-agents-hub-server:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001

  client:
    image: ghcr.io/mcp-agents-ai/mcp-agents-hub-client:latest
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../.github-private/ssl:/etc/nginx/ssl:ro
    depends_on:
      - server
