name: Docker Build and Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build the Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}-server:${{ github.event_name }}-${{ github.ref_name }}-${{ github.sha }} \
                       -t ghcr.io/${{ github.repository }}-server:latest ./server
          docker build -t ghcr.io/${{ github.repository }}-client:${{ github.event_name }}-${{ github.ref_name }}-${{ github.sha }} \
                       -t ghcr.io/${{ github.repository }}-client:latest ./client

      - name: Push the Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}-client:${{ github.event_name }}-${{ github.ref_name }}-${{ github.sha }}
          docker push ghcr.io/${{ github.repository }}-client:latest
          docker push ghcr.io/${{ github.repository }}-server:${{ github.event_name }}-${{ github.ref_name }}-${{ github.sha }}
          docker push ghcr.io/${{ github.repository }}-server:latest
